SELECT FIRST_NAME, SALARY FROM HR.EMPLOYEES WHERE EMPLOYEE_ID=101;
SELECT FIRST_NAME, SALARY FROM HR.EMPLOYEES WHERE EMPLOYEE_ID=102;
EXECUTE DBMS_FLASHBACK.ENABLE_AT_TIME(TO_TIMESTAMP('12/08/2023 16:30:00','DD/MM/YYYY HH24:MI:SS'));
SELECT FIRST_NAME, SALARY FROM HR.EMPLOYEES WHERE EMPLOYEE_ID=101;
SELECT FIRST_NAME, SALARY FROM HR.EMPLOYEES WHERE EMPLOYEE_ID=102;
EXECUTE DBMS_FLASHBACK.DISABLE;
SELECT FIRST_NAME, SALARY FROM HR.EMPLOYEES WHERE EMPLOYEE_ID=101;
SELECT FIRST_NAME, SALARY FROM HR.EMPLOYEES WHERE EMPLOYEE_ID=102;