INSERT INTO hr.regions VALUES (60,'TERCIO');
INSERT INTO hr.regions VALUES (70,'COSTA');
COMMIT;
UPDATE hr.regions SET region_name='TERCIO COSTA'  WHERE region_id = 60;
UPDATE hr.regions SET region_name='GUOB' WHERE region_id = 70;
COMMIT;
UPDATE hr.regions SET region_id=80  WHERE region_id = 60;
COMMIT;

SELECT  VERSIONS_ENDTIME, VERSIONS_OPERATION, VERSIONS_XID, REGION_NAME, REGION_ID 
FROM HR.REGIONS VERSIONS BETWEEN TIMESTAMP MINVALUE AND MAXVALUE WHERE REGION_ID IN (60,70,80);

BEGIN
  DBMS_FLASHBACK.TRANSACTION_BACKOUT(numtxns => 1,
                                     xids    => sys.xid_array('08001C00F8030000'),
                                     options => DBMS_FLASHBACK.CASCADE);
END;
/

SELECT * FROM DBA_FLASHBACK_TXN_STATE;
SELECT XID_REPORT FROM DBA_FLASHBACK_TXN_REPORT;