SHOW PARAMETER recyclebin;
SELECT * FROM HR.JOB_HISTORY;
DROP TABLE HR.JOB_HISTORY;
SELECT * FROM HR.JOB_HISTORY;
SELECT object_name, original_name, type FROM recyclebin;
SELECT * FROM HR.JOB_HISTORY;
FLASHBACK TABLE HR.JOB_HISTORY TO BEFORE DROP;
SELECT * FROM HR.JOB_HISTORY;