SELECT
    VERSIONS_STARTTIME,
    VERSIONS_ENDTIME,
    VERSIONS_OPERATION,
    VERSIONS_XID,
    FIRST_NAME,
    SALARY
FROM
    HR.EMPLOYEES VERSIONS BETWEEN TIMESTAMP TO_TIMESTAMP('12/08/2023 16:40:00','DD/MM/YYYY HH24:MI:SS') AND SYSTIMESTAMP
WHERE
    EMPLOYEE_ID=101;