--
ALTER SESSION SET NLS_DATE_FORMAT='DD/MM/YYYY HH24:MI:SS';
SELECT SYSDATE, CURRENT_SCN FROM V$DATABASE;
SELECT FIRST_NAME, SALARY FROM HR.EMPLOYEES WHERE EMPLOYEE_ID=101;
UPDATE HR.EMPLOYEES SET SALARY=20000 WHERE EMPLOYEE_ID=101;
COMMIT;

SELECT SYSDATE, CURRENT_SCN FROM V$DATABASE;
SELECT FIRST_NAME, SALARY FROM HR.EMPLOYEES WHERE EMPLOYEE_ID=101;
SELECT SYSDATE, CURRENT_SCN FROM V$DATABASE;
SELECT FIRST_NAME, SALARY FROM HR.EMPLOYEES AS OF TIMESTAMP TO_TIMESTAMP('12/08/2023 16:40:00','DD/MM/YYYY HH24:MI:SS') WHERE EMPLOYEE_ID=101;
SELECT FIRST_NAME, SALARY FROM HR.EMPLOYEES AS OF SCN 2281896 WHERE EMPLOYEE_ID = 101;

UPDATE HR.EMPLOYEES SET SALARY=30000 WHERE EMPLOYEE_ID=101;
UPDATE HR.EMPLOYEES SET SALARY=30000 WHERE EMPLOYEE_ID=102;
COMMIT;

SELECT FIRST_NAME, SALARY FROM HR.EMPLOYEES WHERE EMPLOYEE_ID=101;
SELECT SYSTIMESTAMP FROM DUAL;
SELECT FIRST_NAME, SALARY FROM HR.EMPLOYEES AS OF TIMESTAMP TO_TIMESTAMP('12/08/2023 16:43','DD/MM/YYYY HH24:MI') WHERE EMPLOYEE_ID=101;