CREATE TABLESPACE FDA_TS;
ALTER USER HR QUOTA UNLIMITED ON FDA_TS;
CREATE FLASHBACK ARCHIVE DEFAULT FDA1 TABLESPACE FDA_TS RETENTION 1 YEAR;
GRANT FLASHBACK ARCHIVE ON FDA1 TO HR;
EXEC DBMS_FLASHBACK_ARCHIVE.SET_CONTEXT_LEVEL('ALL');
  
CREATE TABLE HR.TESTE_FDA(A NUMBER) FLASHBACK ARCHIVE;
INSERT INTO HR.TESTE_FDA VALUES(1);
COMMIT;
UPDATE HR.TESTE_FDA SET A = 2;
COMMIT;

SELECT * FROM HR.TESTE_FDA;
SELECT * FROM DBA_FLASHBACK_ARCHIVE;
SELECT * FROM DBA_FLASHBACK_ARCHIVE_TS;
SELECT * FROM DBA_FLASHBACK_ARCHIVE_TABLES;

SELECT OWNER, TABLE_NAME FROM DBA_TABLES WHERE TABLE_NAME = 'SYS_FBA_HIST_74912';
select * FROM HR.SYS_FBA_HIST_74877;
SELECT * FROM HR.TESTE_FDA;
SELECT VERSIONS_STARTTIME, VERSIONS_ENDTIME, VERSIONS_OPERATION, VERSIONS_XID, A FROM HR.TESTE_FDA VERSIONS BETWEEN TIMESTAMP MINVALUE AND MAXVALUE;
SELECT versions_startscn,
       versions_starttime, 
       versions_endscn,
       versions_endtime,
       versions_xid,
       versions_operation,
       DBMS_FLASHBACK_ARCHIVE.GET_SYS_CONTEXT(versions_xid, 'USERENV','SESSION_USER') AS session_user,
       DBMS_FLASHBACK_ARCHIVE.GET_SYS_CONTEXT(versions_xid, 'USERENV','MODULE')       AS MODULE,
       DBMS_FLASHBACK_ARCHIVE.GET_SYS_CONTEXT(versions_xid, 'USERENV','IP_ADDRESS')   AS IP_ADDRESS,
       DBMS_FLASHBACK_ARCHIVE.GET_SYS_CONTEXT(versions_xid, 'USERENV','OS_USER')      AS OS_USER,
       DBMS_FLASHBACK_ARCHIVE.GET_SYS_CONTEXT(versions_xid, 'USERENV','SERVER_HOST')  AS SERVER_HOST,
       emp.*
FROM   hr.TESTE_FDA  
       VERSIONS BETWEEN TIMESTAMP MINVALUE AND MAXVALUE emp;